import sword1 from "@/public/images/items/Sword01.png";
import sword2 from "@/public/images/items/Sword02.png";
import sword3 from "@/public/images/items/Sword03.png";
import sword4 from "@/public/images/items/Sword04.png";
import sword5 from "@/public/images/items/Sword05.png";
import sword6 from "@/public/images/items/Sword06.png";
import sword7 from "@/public/images/items/Sword07.png";
import sword8 from "@/public/images/items/Sword08.png";
import sword9 from "@/public/images/items/Sword09.png";
import sword10 from "@/public/images/items/Sword10.png";
import sword11 from "@/public/images/items/Sword11.png";
import sword12 from "@/public/images/items/Sword12.png";
import sword13 from "@/public/images/items/Sword13.png";
import sword14 from "@/public/images/items/Sword14.png";
import sword15 from "@/public/images/items/Sword15.png";
import sword16 from "@/public/images/items/Sword16.png";
import sword17 from "@/public/images/items/Sword17.png";
import sword18 from "@/public/images/items/Sword18.png";
import sword19 from "@/public/images/items/Sword19.png";
import sword20 from "@/public/images/items/Sword20.png";
import sword21 from "@/public/images/items/Sword21.png";
import sword22 from "@/public/images/items/Sword22.png";
import sword23 from "@/public/images/items/Sword23.png";
import sword24 from "@/public/images/items/Sword24.png";
import sword25 from "@/public/images/items/Sword25.png";
import sword26 from "@/public/images/items/Sword26.png";
import sword27 from "@/public/images/items/Sword27.png";
import sword28 from "@/public/images/items/Sword28.png";
import coins from "@/public/images/items/CoinsGold.png";

export const items = {
    ui: {
        coins: {
            image: coins,
            name: "coins",
        }
    },
    weapons: {
        sword1: {
            id: 1,
            type: "weapon",
            attack: 2,
            magicAttack: 0,
            name: "Rusty Blade",
            description: "An old, rusty sword that has seen better days. It may not be the strongest, but it can still cut.",
            equipable: true,
            consumable: false,
            stackable: false,
            image: sword1,
            price: 50,
        },
        sword2: {
            id: 2,
            type: "weapon",
            attack: 4,
            magicAttack: 0,
            name: "Wooden Short Sword",
            description: "A simple wooden sword, light and easy to wield. Ideal for beginners.",
            equipable: true,
            consumable: false,
            stackable: false,
            image: sword2,
            price: 75,
        },
        sword3: {
            id: 3,
            type: "weapon",
            attack: 6,
            magicAttack: 0,
            name: "Iron Edge",
            description: "A sturdy sword made of iron, offering a good balance of weight and sharpness.",
            equipable: true,
            consumable: false,
            stackable: false,
            image: sword3,
            price: 100,
        },
        sword4: {
            id: 4,
            type: "weapon",
            attack: 5,
            magicAttack: 1,
            name: "Frostbite Dagger",
            description: "A dagger imbued with the essence of ice, capable of freezing its foes.",
            equipable: true,
            consumable: false,
            stackable: false,
            image: sword4,
            price: 120,
        },
        sword5: {
            id: 5,
            type: "weapon",
            attack: 8,
            magicAttack: 1,
            name: "Flame Tongue",
            description: "A sword that burns with the fire of a thousand suns, igniting enemies with each strike.",
            equipable: true,
            consumable: false,
            stackable: false,
            image: sword5,
            price: 150,
        },
        sword6: {
            id: 6,
            type: "weapon",
            attack: 7,
            magicAttack: 1,
            name: "Shadow Fang",
            description: "A blade that seems to absorb light, striking fear into the hearts of its enemies.",
            equipable: true,
            consumable: false,
            stackable: false,
            image: sword6,
            price: 140,
        },
        sword7: {
            id: 7,
            type: "weapon",
            attack: 9,
            magicAttack: 2,
            name: "Emerald Cutter",
            description: "A beautifully crafted sword with an emerald embedded in the hilt, known for its sharpness.",
            equipable: true,
            consumable: false,
            stackable: false,
            image: sword7,
            price: 180,
        },
        sword8: {
            id: 8,
            type: "weapon",
            attack: 10,
            magicAttack: 2,
            name: "Silverleaf Sabre",
            description: "A sabre made from silverleaf, light and swift, perfect for quick strikes.",
            equipable: true,
            consumable: false,
            stackable: false,
            image: sword8,
            price: 200,
        },
        sword9: {
            id: 9,
            type: "weapon",
            attack: 12,
            magicAttack: 3,
            name: "Stormbringer",
            description: "A sword that crackles with the power of storms, capable of unleashing thunderous strikes.",
            equipable: true,
            consumable: false,
            stackable: false,
            image: sword9,
            price: 250,
        },
        sword10: {
            id: 10,
            type: "weapon",
            attack: 11,
            magicAttack: 2,
            name: "Guardian's Gladius",
            description: "A gladius that has protected many warriors, known for its durability and strength.",
            equipable: true,
            consumable: false,
            stackable: false,
            image: sword10,
            price: 230,
        },
        sword11: {
            id: 11,
            type: "weapon",
            attack: 14,
            magicAttack: 4,
            name: "Dragon's Claw",
            description: "Forged from the claw of a dragon, this sword is both powerful and fearsome.",
            equipable: true,
            consumable: false,
            stackable: false,
            image: sword11,
            price: 300,
        },
        sword12: {
            id: 12,
            type: "weapon",
            attack: 13,
            magicAttack: 3,
            name: "Viper's Strike",
            description: "A swift sword that strikes like a viper, delivering quick and deadly blows.",
            equipable: true,
            consumable: false,
            stackable: false,
            image: sword12,
            price: 280,
        },
        sword13: {
            id: 13,
            type: "weapon",
            attack: 15,
            magicAttack: 5,
            name: "Celestial Longsword",
            description: "A long sword blessed by the stars, it shines with a celestial light.",
            equipable: true,
            consumable: false,
            stackable: false,
            image: sword13,
            price: 350,
        },
        sword14: {
            id: 14,
            type: "weapon",
            attack: 16,
            magicAttack: 6,
            name: "Bloodletter",
            description: "A sword that thirsts for blood, known for its lethal efficiency in battle.",
            equipable: true,
            consumable: false,
            stackable: false,
            image: sword14,
            price: 400,
        },
        sword15: {
            id: 15,
            type: "weapon",
            attack: 18,
            magicAttack: 7,
            name: "Wyrm's Tooth",
            description: "A fearsome sword made from the tooth of a wyrm, it carries the essence of the beast.",
            equipable: true,
            consumable: false,
            stackable: false,
            image: sword15,
            price: 450,
        },
        sword16: {
            id: 16,
            type: "weapon",
            attack: 17,
            magicAttack: 8,
            name: "Moonlit Blade",
            description: "A blade that glows under the moonlight, enhancing the wielder's agility.",
            equipable: true,
            consumable: false,
            stackable: false,
            image: sword16,
            price: 420,
        },
        sword17: {
            id: 17,
            type: "weapon",
            attack: 19,
            magicAttack: 11,
            name: "Thunderstrike",
            description: "A sword that channels the power of thunder, delivering electrifying strikes.",
            equipable: true,
            consumable: false,
            stackable: false,
            image: sword17,
            price: 500,
        },
        sword18: {
            id: 18,
            type: "weapon",
            attack: 20,
            magicAttack: 12,
            name: "Soul Reaver",
            description: "A dark sword that can drain the life force of its enemies.",
            equipable: true,
            consumable: false,
            stackable: false,
            image: sword18,
            price: 550,
        },
        sword19: {
            id: 19,
            type: "weapon",
            attack: 21,
            magicAttack: 13,
            name: "Phoenix Feather Sword",
            description: "A sword imbued with the essence of a phoenix, it can ignite the spirit of its wielder.",
            equipable: true,
            consumable: false,
            stackable: false,
            image: sword19,
            price: 600,
        },
        sword20: {
            id: 20,
            type: "weapon",
            attack: 22,
            magicAttack: 14,
            name: "Spectral Blade",
            description: "A ghostly sword that can cut through the fabric of reality itself.",
            equipable: true,
            consumable: false,
            stackable: false,
            image: sword20,
            price: 650,
        },
        sword21: {
            id: 21,
            type: "weapon",
            attack: 23,
            magicAttack: 15,
            name: "Titan's Bane",
            description: "A colossal sword designed to slay titans, it is heavy but immensely powerful.",
            equipable: true,
            consumable: false,
            stackable: false,
            image: sword21,
            price: 700,
        },
        sword22: {
            id: 22,
            type: "weapon",
            attack: 24,
            magicAttack: 16,
            name: "Voidwalker",
            description: "A sword that allows its wielder to traverse the void, striking from unexpected angles.",
            equipable: true,
            consumable: false,
            stackable: false,
            image: sword22,
            price: 750,
        },
        sword23: {
            id: 23,
            type: "weapon",
            attack: 25,
            magicAttack: 17,
            name: "Blade of the Ancients",
            description: "An ancient sword that holds the wisdom of the ages, granting its wielder unmatched skill.",
            equipable: true,
            consumable: false,
            stackable: false,
            image: sword23,
            price: 800,
        },
        sword24: {
            id: 24,
            type: "weapon",
            attack: 26,
            magicAttack: 18,
            name: "Cursed Edge",
            description: "A sword cursed by dark magic, it grants great power at a terrible cost.",
            equipable: true,
            consumable: false,
            stackable: false,
            image: sword24,
            price: 850,
        },
        sword25: {
            id: 25,
            type: "weapon",
            attack: 27,
            magicAttack: 19,
            name: "Abyssal Blade",
            description: "A blade forged in the depths of the abyss, it consumes the souls of its victims.",
            equipable: true,
            consumable: false,
            stackable: false,
            image: sword25,
            price: 900,
        },
        sword26: {
            id: 26,
            type: "weapon",
            attack: 28,
            magicAttack: 20,
            name: "Ethereal Sword",
            description: "A sword that exists between realms, it can strike both physical and spiritual foes.",
            equipable: true,
            consumable: false,
            stackable: false,
            image: sword26,
            price: 950,
        },
        sword27: {
            id: 27,
            type: "weapon",
            attack: 29,
            magicAttack: 21,
            name: "Blade of Destiny",
            description: "A legendary sword said to choose its wielder, granting them the power to shape their fate.",
            equipable: true,
            consumable: false,
            stackable: false,
            image: sword27,
            price: 1000,
        },
        sword28: {
            id: 28,
            type: "weapon",
            attack: 30,
            magicAttack: 22,
            name: "Legendary Excalibur",
            description: "The fabled sword of kings, it is said to bestow unmatched power upon its rightful owner.",
            equipable: true,
            consumable: false,
            stackable: false,
            image: sword28,
            price: 1200,
        },
    }
};